### ISSUE TITLE
Fix ePUB date issues

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#268]
File: `daps_xslt/epub/db2db.xsl`

If the XML source contains a <?dbtimestamp?> PI, an empty `dc:date` element is generated in the ePUB.

**Comment by tomschr** [comment]
This is the implementation idea:
- when a `<date>` element is missing, create a `<date>`.  If parameter `$use.pi4date != 0` create a PI with format="Y-m-d", otherwise create the current date.
- when a `<date>` element exists with a PI of `dbtimestamp`, create a `<date>` element. If the format string is ok, use it, otherwise fallback to `format="Y-m-d"`.
- when a `<date>` element exists but without a PI, check the string. If the string conforms to certain format, use it, otherwise use the current date and give a warning.
