### ISSUE TITLE
Critical: Fo contains wrong image paths when XML contains no profiling PI

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#316]
When MAIN does not contain a profiling PI image paths in the FO file point to 
`<...>/build/.profiled/noprofile/<IMAGE>` rather than to `<...>/build/.images/color/<IMAGE>.

**Comment by fsundermeyer** [comment]
The reason seems to be that `$(DAPSROOT)/daps-xslt/profiling/noprofile5.xsl` and probably also `$(DAPSROOT)/daps-xslt/profiling/noprofile4.xsl` do not add `xml:base="<filename>"` to the root element of the profiled file.

Toms, is that something you can fix?

**Comment by tomschr** [comment]
> [...the stylesheet ...] do not add xml:base="<filename>" to the root element of the profiled file.

I see.

> Toms, is that something you can fix?

It's is not a problem to add an `xml:base` attribute to the root element. The problem is the attribute _value_:
There is no XPath 1.0/XSLT 1.0 function to retrieve the absolute path of an XML file. This is only available in XSLT/XPath 2.0.

For that reason, we introduced in the profiling stylesheets the `filename` attribute (see `base-profile.xsl`). In the file [`make/profiling.mk`](https://github.com/openSUSE/daps/blob/develop/make/profiling.mk#L94) you pass that parameter to the profiling stylesheet. There is no parameter in the `noprofile*.xsl` stylesheets.

I will add an `xml:base` attribute into the root element with the value from the `$filename` parameter. In the best case you don't have to do anything (see the previous paragraph) as the parameter is already passed. Hope you can confirm my analysis. :grinning:

**Comment by tomschr** [comment]
See the above commit: If no `xml:base` attribute is available in the root element, it's created with the content from the `$filename` parameter.
