### ISSUE TITLE
Doc: Translation check for locdrop

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#324]
See  #306

**Comment by taroth21** [comment]
@fsundermeyer: I just checked: We commented 'sec.daps.user.review.locdrop' in daps_user_review.xml last time because we (you) assumed the locdrop function would be too SUSE-specific to be useful for external DAPS users. If you think we should revert that decision, I can add a fix for this issue, otherwise I suggest to close it.

**Comment by fsundermeyer** [comment]
See comment above. locdrop not in docs. WONTFIX
