### ISSUE TITLE
DAPS fails to validate MAIN files if their name does not match *.xml

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#344]
For some reason, DAPS enforces that you name all you DocBook XML files `*.xml`, and does not accept e.g. `*.tmp` even when those files are actually valid XML files. I tried this:

```
$ daps -m xml/release-notes.tmp validate

/usr/share/daps/make/validate.mk:24: recipe for target 'validate' failed
make: *** [validate] Error 1
```

Same file, renamed & it worked:

```
daps -m xml/release-notes2.xml validate
```

---

Interestingly, as long as my `*.tmp` file still had invalid entities, DAPS would tell me about the entity issues. But as soon as it was well-formed, it failed.

**Comment by fsundermeyer** [comment]
Fixed filename suffixes for xml files and graphics as well as a predefined directory structure are pre-requisites that must be met. SInce DAPS is based on `make` in large parts, it must follow the make standards. And one of them is that make converts files from type A to type B. Since make has no magic to determine a filetype, it relies on file suffixes.
So this is a WONTIFIX.
