### ISSUE TITLE
Why does spec file include BuildRequires for "fdupes," "ghostscript," "inkscape," "ImageMagick," "dia"?

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#350]
BuildRequires in subject seem pretty random -- does building DAPS really need this many image-related tools?

**Comment by ghost** [comment]
Okay, at least part of those seem necessary for building the DAPS documentation...

**Comment by cwickert** [comment]
Site note: xerces-j2 should be pulled in through some dependency chain, but it's no longer. We either need to fix whatever package is supposed to pull it in or make it a daps requires directly.

**Comment by fsundermeyer** [comment]
Closing as invalid.
- fdupes replaces file duplicates with links when creating the package
- inkscape nad imageMagick are needed for various image file conversions (svg -> png for example)
- ghostscript is needed to generate "PDF images"
- dia is needed because we support the dia image file format (same goes fpr xfig)

I will add a separate bug for the missing xerces-j2 dependency...
