### ISSUE TITLE
Add a command to list unused images

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#352]
Would be great to have for cleanups, etc.

Ideally it would have the option to look across all DC files in the directory.

**Comment by fsundermeyer** [comment]
This is already implemented with `daps list-srcfiles-unused --imgonly`

However, it only makes sense in a directory containing a single DC-file or a single set witha DC-file referencing the whole set. Otherwise images would be listed that may be used in files not referenced by the current DC-file. That would be fatal if the function would be used for cleanups.
Unfortunately DAPS can only operate on a single DC-file ...

One may also want to keep images that currently appear in comments in the XML sources (they may only have been temporarily disabled). The following bash commands create a list of images that are neither actively or "passively" (in comments) used:

```
# images in manuals
for dc in DC-*; do 
  daps -d $dc list-srcfiles --imgonly  --pretty
done | sort -u > images_manuals.txt

# images in repository
find images/ -type f | sed "s:^:$(pwd)/:" | sort > images_repo.txt

# get potentially obsolete images
comm -13 images_manuals.txt images_repo.txt | sort > images_obsolete.txt

# check if potentially obsolete images appear in comments (we want to keep those)
for LINE in $(cat images_obsolete.txt); do
  TMP=${LINE##*/}
  IMG=${TMP%.*}
  [[ $(grep -A3 imagedata xml/*.xml | grep "$IMG") ]] && echo $LINE >> images_in_comments.txt
done

# get images that can be deleted
comm -13 images_in_comments.txt images_obsolete.txt > images_delete.txt
```

I could create a separate script creating a list of really obsolete image files by creating a script from the code listed above, if needed, but it is not possible to implement it as a dasp function.

Please let me know if you want such a script...
