### ISSUE TITLE
DocBook5: Allow validating without checking xrefs

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#364]
For debugging purposes it sometimes is useful, to process documents even if xref links are invalid.

Jing supports the "-i" switch which allows to validate without checking for xrefs (xmllint does _not_ allow this, so this is for DB5 only).

**Comment by fsundermeyer** [comment]
Fixed with commit   0f4fb6d, handing over to documentation.

**Comment by stefanq** [comment]
I cannot find how to activate this option, neither in the user guide nor from "daps -h" or /etc/daps/config.
Any hints?

**Comment by ghost** [comment]
@stefanq Take a look at the linked commit c77fa99 above in which this was added to the user guide. (We still need to sync the user guide, I guess.)

**Comment by fsundermeyer** [comment]
@stefanq This feature can be used with the validate and all subcommands that create output formats (html, pdf, epub, text, man, bigfile):

      daps -d <DC> html --single --norefcheck

Since this is a subcommand option, you only see it in help, if you call help for a subcommand (e.g. `daps html --help`).

----------- HERE BE DRAGONS! ------------

You can also set this in the DC-file or in `~/.config/daps/dapsrc` or `/etc/daps/config` with

      NOREFCHECK=1

However, I would not recommend to do so. Temporary setting this in a DC-file or a special draft version of a DC-file may make sense, but setting this in the other config files will make this setting the default for all builds done by DAPS. This will make it impossible to detect broken links by DAPS unless you explicitly set `NOREFCHECK=0` on the command line or in the DC files.
For this reason I'd rather prefer not to document the NOREFCHECK variable and have also not added it to /etc/daps/config

**Comment by stefanq** [comment]
@fsundermeyer Thanks for the in-depth documentation!

> Temporary setting this in a DC-file or a special draft version of a DC-file may make sense

Yes, especially for people (me) who use a dedicated DC-chapter for quicker turnarounds of a single chapter XML file (of a >300 pages manual) currently being worked on.

> For this reason I'd rather prefer not to document the NOREFCHECK variable

I agree with you, that the benefit of this feature is not only for debugging purpose for developers.
Therefore I'd suggest to document this option and the use case to encourage users to use NOREFCHECK especially for such cases (quickly building a section, chapter or whatever preview). Because turnaround cycles for long documents take a long time (and for building PDF even more than HTML).
