### ISSUE TITLE
Don't know what gentext to create for xref to: "property"

### ISSUE THREAD

**Issue by mercadopatricio** [openSUSE/daps#417]
### Problem description
Hi, just trying to crossreference a <property></property> tag. In pdf output only appear "?????" text.

Code example:
`<para>This is a <property id="propertytest">test</property></para>
<para><xref linkend="propertytest"/></para>`

Output:
`This is a ???`   ("test" word doesn't appear)

### Expected behavior
`This is a _test_`   ("test" word literally as a text taking text from source)

### Steps to reproduce the behavior
1) daps-init empty or with example project
2) Add example xml
3) daps -v pdf

console say:
`Don't know what gentext to create for xref to: "property"`

And ??? chars in pdf file.

**Comment by ghost** [comment]
This is a stylesheet issue -- even the original DocBook stylesheets don't create useful ID refs for `property`.

I am closing this here, since this is not a DAPS bug but clearly stylesheet territory. Please report this upstream at https://github.com/docbook/xslt10-stylesheets/issues (I checked with those stylesheets and it does not work with those, also definitely won't work with the SUSE version therefore.)
