### ISSUE TITLE
Asciidoc color formatting is ignored and replaced

### ISSUE THREAD

**Issue by tgeek77** [openSUSE/daps#500]
### Problem description
Asciidoc color formatting is ignored and replaced
### Expected behavior
Asciidoc color formatting should be interpreted as it is meant.
### Steps to reproduce the behavior

Example code:
```
. Run the following command to configure this as a Kubernetes master
node:
+
`[blue]*kubeadm init --cri-socket=/var/run/crio/crio.sock \*`
{nbsp} +
`[blue]*--pod-network-cidr=10.244.0.0/16*`
+
```
This should should two commands with bold blue text in monospace. I confirmed this with asciidoc preview in both the Atom editor and the AsciidocFX editor

Daps interprets this code as bold black text in monospace and underlined. 

If a different code should be used with daps, I can try it, but this seems to be a legitimate command per the asciidoc manual. If this is because of the stylesheet overriding the asciidoc command, is there a way to make what's in the actual code explicit?

Actual file can be found here:
https://raw.githubusercontent.com/tgeek77/kubic-quickstart/master/lab/adoc/EXERCISE-Bootstrap_Cluster-v01.adoc

**Comment by fsundermeyer** [comment]
Hi Jason,

just had a look at how the color codes get transformed into DocBook:

&lt;phrase role="blue">TEXT&lt;/phrase>

Unfortunately this is not supported by our stylesheets (and also not by the DocBook upstream stylesheets) and therefore ignored.

@tomschr @sknorr : How much effort would it be to add such support to our stylesheets and geekodoc? The following 16 color names are supported: https://en.wikipedia.org/wiki/Web_colors#HTML_color_names
Any objections adding this to our schema/stylesheets?

**Comment by fsundermeyer** [comment]
BTW: Congratulations for creating issue number 500 !! ;-D

**Comment by fsundermeyer** [comment]
Jason, 

I just talked to our stylesheet developers. We currently have 226 open issues in https://github.com/openSUSE/suse-xsl, so for the moment we do not see a way to get color coding implemented - there is a lot of issues that have higher priority at the moment.

We are supporting preformatted text with our stylesheets and use this for command, programlistings and shell output. So, as an alternative, you coud use something like

     Run the following command to configure this as a Kubernetes 
     master node:

    [source]
    ----
    kubeadm init --cri-socket=/var/run/crio/crio.sock \
    --pod-network-cidr=10.244.0.0/16
    ----

Would that work for you?

**Comment by ghost** [comment]
This is an AsciiDoc feature that has no equivalent in DocBook. It is only mentioned in the AsciiDoc User Guide for the outdated asciidoc tool (http://methods.co.nz/asciidoc/userguide.html). It seems it is not mentioned in the AsciiDoctor guides (https://asciidoctor.org/docs) and not working with DAPS/AsciiDoctor.

DAPS currently supports both the asciidoc and the asciidoctor tool, but their output is not always compatible and only asciidoctor is still actively maintained whereas asciidoc is a Python 2 tool that will soon be removed or at least significantly less available in SUSE distributions.

I'd suggest to close this one since even our (new) upstream AsciiDoc conversion tool does not support it.

**Comment by ghost** [comment]
No answer for two weeks -> closing.
