### ISSUE TITLE
AsciiDoc Monospace formatting

### ISSUE THREAD

**Issue by tgeek77** [openSUSE/daps#503]
I know there is a long backlog of issues, but I figure that it's better to report this than not to.

### Problem description
Bold monospace and Italic monospace are represented as underlines instead of just their respective values

### Expected behavior
See above

### Steps to reproduce the behavior
[AsciiDoc source](https://raw.githubusercontent.com/tgeek77/kubic-quickstart/master/lab/adoc/conventions.adoc)

The attached file, [asciidoctor_daps.pdf](https://github.com/openSUSE/daps/files/3106957/asciidoctor_daps.pdf), has the output from asciidoctor-pdf (Page 1) and DAPS (Page 2) side by side.

**Comment by ghost** [comment]
1. Monospace italics look as expected (which interestingly they do not in AsciiDoctor's PDF output)
2. Monospace bold in the source is \*\`text\`\* instead of the version correctly reproduced in the middle column: \`\*text\*\` (yes, that markup is tricky and we could potentially use the post-processing stylesheet to fix this but I am a bit unsure about this)
3. We use underlines under *all* inline monospace text because a lot of people tend to miss font changes and make them more obvious, especially in HTML output where mono and sans are relatively similar.

Imo, works as expected.

Feel free to re-open. (I hope you have the right to do that -- otherwise open a new bug)
