### ISSUE TITLE
Remove dm:docmanager block for locdrops

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#533]
xmlstarlet ed --inplace -N dm="urn:x-suse:ns:docmanager" -N db5="http://docbook.org/ns/docbook" -d "//dm:docmanager" foo.xml

(maybe add a command line option for keeping it)

**Comment by ghost** [comment]
I am guessing you don't need to define the DocBook namespace. Alternatively, if you do, you should probably define the XLink and XInclude namespaces as well.

**Comment by taroth21** [comment]
Reasoning behind this: We mostly cannot tell if bug reports or pull requests in foreign languages are correct, so why collect them in the first place? 

In addition, this saves a lot of hassle with the translated files:

- If content of `<dm:component/>` is translated it breaks the link to Bugzilla (or another bugtracker)  because the respective strings must be the same as in Bugzilla.
- We don't need to adjust `<dm:editurl/>` in the translated sources (would need to point to respective 'trans' branch and correct language otherwise).
- We do not need to switch the Bugzilla link from the 'Beta' version to the 'normal' version (either before locdrop or in the translated sources).
