### ISSUE TITLE
prevent `link linkend` in asciidoc

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#545]
AsciiDoc's `<<some_id, A Title>>` is converted to `<link linkend="some_id">A title</link>`.
`link linkend` is not GeekoDoc-compatible or compatible with our stylesheets. Can we convert to `xref linkend` with the title removed using the compatibility XSLT that we have?

Related: https://github.com/openSUSE/suse-xsl/issues/244

(via @r0ckarong)

**Comment by fsundermeyer** [comment]
@r0ckarong Please use `xref:SOME_ID[]` in asciidoc rather than <<SOME_ID>>. Ths will create xrefs in XML.

**Comment by r0ckarong** [comment]
So does this mean we generally can't use the `<<SOME_ID>>` format anymore?

**Comment by ghost** [comment]
Imo, no, `<<some_id>>` is fine, it generates the same DocBook that `xref:some_id[]` does.

**Comment by fsundermeyer** [comment]
Oh, overlooked that it is &lt;&lt;some_id, A Title>> only. What's worse xref:SOME_ID[TEXT] also generates &lt;&lt;linkend> tags.

Will close this as wontfix, because there should be no need to use <<some_id, A Title>>. In case it seems necessary, rephrasing the sentence or the link title is always an option. The same policy applies for our DocBook sources.

@sknorr If you really think this needs fixing, feel free to add a rule to daps-xslt/asciidoc/postprocess.xsl. Although, removing the title would be a no-go, since that would alter the text and will eventually result in sentences that no longer make sense, e.g. if you have something like:

`Find more information about <<cut_text, Cut>> & <<paste_text, Paste>> here.`

Which then may result in something like

Find more infomation about Xselection; Cutting text using mouse and keyboard, Desktop Guide, page 231 & Xselection; Pasting text by middle mouse click, Desktop Guide, page 233 here.

**Comment by ghost** [comment]
1231593 fixes this in the postprocess stylesheet too now.
