### ISSUE TITLE
Asciidoc output does not include xml:base attribute, so dm:editurl and other features are broken

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#561]
### Problem description

When Asciidoctor generates XML files, it does not add any xml:base attributes to the document. Unfortunately, a couple of document features implemented in DAPS, the style checker, and the stylesheets themselves really need the xml:base attributes. 

(reported through @chabowski )

### Expected behavior

* Ideally, this would be fixed at the AsciiDoctor XML-export level, generating xml:base elements for each Asciidoc include statement.
* Failing that, we should at least set an xml:base attribute at the root of the document somewhere during the DAPS run. That's going to be misleading for longer documents, like the CaaSP guides. But it's going to be good enough for our SBPs at least.

### Steps to reproduce problem

* Add a `<dm:editurl/>` element to your DocManager tags, format as HTML with the stylesheets, see that nothing happens
* Try running DAPS with `--meta` and see that you're getting way too little info in the output documents.
* Run `daps stylecheck` on a document and don't get document references.

**Comment by fsundermeyer** [comment]
When converting asciidoc into DocBook XML a single XML file is created, so xml:base attributes do not make sense - where should they point to?
Also source editing from HTML (which was generated using the above mentioned DocBook file) will not work, since there is no relation between the DocBook file and the asciidoc sources. IMVALID
