### ISSUE TITLE
`link:https://domain/foo#bar#baz[]` considered invalid

### ISSUE THREAD

**Issue by KucharczykL** [openSUSE/daps#597]
Filed on behalf of Andreas Färber, originally reported in the SLES RN repository.

### Problem description

The following link with two hashtags, which was copied from Firefox,
```
link:pass:[https://docs.nvidia.com/jetson/l4t/index.html#page/Tegra Linux Driver Package Development Guide/bootflow_jetson_xavier.html#wwpID0E0FB0HA][CBoot bootloader]
```
leads to a validation error:
```
$ LANG=C make LIFECYCLE=beta validate
daps -d DC-release-notes \
  --adocattr lifecycle=beta \
  validate
/home/afaerber/release-notes-sles/build/.profiled/noprofile/release-notes.xml:2144:207: error: value of attribute "xl:href" is invalid; must be a URI
make[1]: *** [/usr/share/daps/make/validate.mk:40: validate] Error 1
make: *** [Makefile:45: validate] Error 2
```

If I remove the last hashtag, it validates and builds, but not the desired link target gets displayed on that page.

### Expected behavior

The validation passes.

### Steps to reproduce problem

1. Include this code in an .adoc file:
```
link:pass:[https://docs.nvidia.com/jetson/l4t/index.html#page/Tegra Linux Driver Package Development Guide/bootflow_jetson_xavier.html#wwpID0E0FB0HA][CBoot bootloader]
```
2. Run `make single-html`.
3. Observe validation error.

### Additional information

Replacing `#` with its percent-encoded version (`%23`) validates, builds and works as expected when clicking the link.

**Comment by ghost** [comment]
Normally, # characters are used to separate the normal URL (interpreted by the server) from the anchor/ID segment (interpreted by the client)--you can see that in the Developer Tools of your browser: instead of requesting `https://docs.nvidia.com/jetson/l4t/index.html#page/Tegra Linux Driver Package Development Guide/bootflow_jetson_xavier.html#wwpID0E0FB0HA`, your browser will only request `https://docs.nvidia.com/jetson/l4t/index.html`, redirecting to the actual target page will have to be performed via JS. Similarly, `window.location.hash` will give `#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/bootflow_jetson_xavier.html#wwpID0E0FB0HA` for this page.

In any case, there should normally only be a single `#` character in a URL.

NVIDIA are definitely abusing the URL scheme a bit (which you can also see from the fact that there are two HTML pages mentioned in the URL successively). I am not sure whether that abuse is spec-compliant like e.g. `https:///////` is or whether it's not spec-compliant. We should probably determine compliance here and then try to see if ~~AsciiDoctor~~ [EDIT:] **jing** needs to be fixed.

**Comment by fsundermeyer** [comment]
Unfortunately there is little I can do about this, since it is "jing", the external tool I am using for validation, that reports this as an error. And as Stefan explains above, it seems to be right.

However, there is an easy workaround--just URl-escape the second hashmark with `%23`.

```
link:pass:[https://docs.nvidia.com/jetson/l4t/index.html#page/Tegra Linux Driver Package Development Guide/bootflow_jetson_xavier.html%23wwpID0E0FB0HA][CBoot bootloader]
```

**Comment by KucharczykL** [comment]
Thank you for looking into it!

I've only found this old discussion about this: https://lists.w3.org/Archives/Public/public-rdf-in-xhtml-tf/2008Nov/0043.html

It mentions that the spec disallows the use of # in the fragment part of the URI, however the regex that checks this does not, contradicting itself. I haven't read the spec myself or tried to do more research, though.

**Comment by afaerber** [comment]
I agree with the assessment that within the fragment it may need to be escaped as `%23`, but shouldn't that be handled by ASCIIDoc when using `pass[]`, same way it escapes whitespace as `%20`? The validation appears to fail on some XML file rather than on the original ASCIIDoc input file.

**Comment by fsundermeyer** [comment]
When creating DocBook XML from the adoc sources, asciidoctor does not escape the "#" (nor the spaces). The generated XML contains the link as it was entered in the asciidoc file.
Whatever syntax of the link macro I tried, the result in the XML is always the same.

(You may try yourself with `asciidoctor -b docbook 5 -o test.xml <FILE>.adoc`)

**Comment by fsundermeyer** [comment]
I have tested a few different notations of the link macro directly with asciidoctor. When asciidoctor converts the adoc to DocBook 5 (and that is exactly what happens in DAPS), it does not escape anything. The URL in the XML appears exactly as it was entered in the adoc document.

In case you want to test yourself: 
`asciidoctor -b docbook5 -o test.xml <FILE>.adoc`
