### ISSUE TITLE
Rename variable PDFNAME

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#599]
PDFNAME (set with --name) allows to set a custom filename for the resulting book.
PDFNAME is misleading, since it applis to all outpout formats.

Maybe RESULT_FILENAME?

**Comment by ghost** [comment]
Awesome timing! I'd already opened https://github.com/openSUSE/docserv/issues/258 (which is a combined issue, because Docserv2 is inconsistently renaming things sometimes & DAPS's PDFNAME is imperfect). I did not realize that PDFNAME applies to all output names--but this is great!

I'd like to throw the suggestion OUTPUTNAME in the ring, but RESULT_FILENAME works for me too.

--

The only documents that I know of that we still need and are using the PDFNAME attribute are a few SLES 11 SP4 documents.
Updating those few DCs to a new name should be trivial.

**Comment by ghost** [comment]
fixed in be8a7ca
