### ISSUE TITLE
Add option to open guide in default browser after building

### ISSUE THREAD

**Issue by tahliar** [openSUSE/daps#630]
When building a guide, it would be nice to be able to add something like `--open` so that the built guide automatically opens in my default browser. Sure, I can open it myself, but it'd be quicker if DAPS could do it for me.

**Comment by fsundermeyer** [comment]
It is actually possible by using $() on the shell. Would that work for you?

    chromium $(daps -d DC-foo html --single)
    evince $(daps -d DC-bar pdf)

Whenever daps is not called from a terminal (like in the examples above or in a pipe) it suppresses every additional output and only returns one line (usually a filename or directory).

**Comment by tahliar** [comment]
That works quite well, thank you. 

It would still be easier to have the option in the tool itself, but this is not a critical request by any means, just a nice-to-have suggestion.

**Comment by ghost** [comment]
`chromium $(daps -d DC-foo html --single)`  does not even really work.
You need to use `chromium $(daps -d DC-foo html --single)/index.html`.

But I guess we've gone over that topic before (not sure in which issue though). :)

**Comment by fsundermeyer** [comment]
It is possible to open a resulting file with xdg-open directrly from the makefile, but daps (or rather make) then will wait for the  xdg-open process to terminate before it terminates itself (meaning you would have to close the viewer application to end the daps process). I am not sure this is wanted.
Also, one cannot export the resulting filename from make back into the daps script in order to call xdg-open from the script. Result filenames are generated within make.
Therefore, this is a WONTFIX
