### ISSUE TITLE
DC files: Should line continuation really be allowed on all attributes?

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#651]
On some attributes, like MAIN or ROOTID, line continuations with `+=` make very little sense. For these values, they usually also can't work:

```
MAIN=boo
MAIN+=k.xml
```
-> MAIN is being set to `boo k.xml` (with a space in the middle). DAPS, being allergic to spaces, will obviously not abide and output an error, irregardful of whether `boo k.xml` exists.

Imo line continuation only makes sense for ADOC_ATTRIBUTES and XSLTPARAM. For PROF\*, it could make sense if the space was not being added in the middle.

Not 100% sure how to fix this but I think it might be helpful to enable the functionality only for some attributes and reject DC files that use them for MAIN, ... etc. with an error.

**Comment by ghost** [comment]
> For PROF*, it could make sense if the space was not being added in the middle.

Ftr, I looked at the profiling code yesterday and unless DAPS does anything special, DocBook's XSL code completely fails on spaces.

**Comment by fsundermeyer** [comment]
IMHO the example above is a bit far fetched and covered, since DAPS would throw an error for a non-existing MAIN. DAPS is using a general parser for parsing DC values, only allowing continuation for certain key/value pairs would require more specific code and a lot more maintenance effort.
I do not see a benefit in this, WONTFIX
