### ISSUE TITLE
Add Tutorials For Certain Topics [sf#75]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#75]
**Reported by taroth21 on 2012-05-15 14:53 UTC**
Idea: in addition to User Guide, create tutorials for certain topics (using consistent examples)?

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2012-05-18 06:43**
- **assigned_to**: Tanja Roth

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-03 09:40**
- **labels**: Documentation --> doc

**Comment by taroth21** [comment]
We have a general tutorial (https://github.com/openSUSE/daps/blob/develop/doc/xml/art_daps_tutorial.xml), though we do not officially ship it ATM.

@tomschr, @fsundermeyer, @sknorr: Should we ship this tutorial? Or any suggestions about a certain topic you want a tutorial on? Otherwise I would close this issue.

**Comment by ghost** [comment]
Let's close. This is extremely underdefined
